"""add papers to SECAP

Revision ID: f99f044a40f2
Revises: 6dc5ce79800a
Create Date: 2024-06-24 17:28:30.082760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f99f044a40f2'
down_revision: Union[str, None] = '6dc5ce79800a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        INSERT INTO papers (id, title, authors, area, is_ignored, event_id)
        VALUES
        (66, 'A RETÓRICA DO RETROCESSO: UMA ANÁLISE DOS ARGUMENTOS TRAZIDOS NO PROJETO DE LEI Nº 5167/2009 PARA PROIBIR O CASAMENTO HOMOAFETIVO', 'Bruno Erick Silva Martins; Guilhermino Jordão Brayner de Oliveira; Jackson Vinícius Flor de Albuquerque; João Victor Ferreira Leal', 'Ciências Sociais Aplicadas', false, 2),
        (67, 'O ALUNO NÃO TEVE ENSINO DE QUALIDADE - PERSCRUTANDO CRENÇAS LINGUÍSTICA DE PROFESSORES DO ENSINO FUNDAMENTAL II', 'Marcus Garcia de Sene', 'Linguística - Letras e Artes', false, 2),
        (68, 'REALIDADE VIRTUAL E ABA: HABILIDADES MOTORAS EM CRIANÇAS COM TEA', 'Charles Henrique Andrade de Oliveira', 'Ciências Humanas', false, 2),
        (69, 'NOVAS PERSPECTIVAS EDUCACIONAIS: O PIBID NA FORMAÇÃO DOCENTE DE UM ESTUDANTE DE LETRAS.', 'João Pedro oliveira Bichara', 'Ciências Humanas', false, 2),
        (70, 'COMPORTAMENTO DA VÍTIMA: UMA ANÁLISE RETÓRICA ACERCA DAS DIRETRIZES DOSIMÉTRICAS DA PENA', 'Emanuel Vitor Leitão de Oliveira, Kaua José da Silva Araujo, Lucas Gabriel Silva de Siqueira, Pedro Henrique de Carvalho Siqueira, Pedro Herique Teotônio Pessoa, Pablo Ricardo de Lima Falcão', 'Ciências Humanas', false, 2),
        (71, 'ISOFLAVONAS DA SOJA E SEUS EFEITOS POSITIVOS NO CLIMATÉRIO: UMA REVISÃO BIBLIOGRÁFICA', 'Pedro Henrique Santos de Lima, Layza Amanayara Galdino Figueiredo Marques, Erika Patricia Santos da Silva Teotônio', 'Ciências da Saúde', false, 2),
        (72, 'DESVELANDO A VULNERABILIDADE INFANTIL NO CONTEXTO DO NORDESTE BRASILEIRO: UMA ANÁLISE PELA ÓTICA DA ESCALA BRASILEIRA DE INSEGURANÇA ALIMENTAR', 'Pedro Henrique Santos de Lima, Layza Amanayara Galdino Figueiredo Marques, Erika Patrícia Santos da Silva Teotônio', 'Ciências Sociais Aplicadas', false, 2),
        (73, 'PROPOSIÇÕES INICIAIS SOBRE AS MULHERES NEGRAS PERSEGUIDAS PELA INQUISIÇÃO NO GRÃO-PARÁ NA SEGUNDA METADE DO SÉCULO XVIII', 'Juliane de Miranda Souza', 'Ciências Humanas', false, 2),
        (74, 'CHATGPT: CONSTRUINDO PONTES DE ENTENDIMENTO E USO ÉTICO DA INTELIGÊNCIA ARTIFICIAL NA PESQUISA ACADÊMICA', 'Valdiele da Silva Santos', 'Ciências Sociais Aplicadas', false, 2),
        (75, 'GRAVITROPISMO E SUA IMPLICAÇÃO NO DIRECIONAMENTO DO CRESCIMENTO EM PLANTAS', 'MARIA FERNANDA TAVARES DE ARAÚJO, Rhabersh Sales Rodrigues Pascoal, Gabriel Santos da Silva, Mirelle Cristina Cosme de Araújo, Lucas Felix Cabral da Silva, Ramon da Silva de Souza', 'Ciências Biológicas', false, 2),
        (76, 'RIO TIMBÓ E A INFLUÊNCIA DOS EMPREENDIMENTOS EM ÁREAS COSTEIRAS', 'Rhabersh Sales Rodrigues Pascoal, Gabriel Santos da Silva, Lucas Felix Cabral Da Silva, Maria Fernanda Tavares de Araújo, Mirelle Cristina Cosme de Araújo, Ramon da Silva de Souza', 'Ciências Biológicas', false, 2),
        (77, 'AVALIAÇÃO DO HORMÔNIO ETILENO NO AMADURECIMENTO DE FRUTOS (GÊNERO MUSA) E (GÊNERO MALUS) EXPOSTOS A CONDIÇÕES AMBIENTAIS DIFERENTES', 'Mirelle Cristina Cosme de Araújo, Maria Fernanda Tavares de Araújo, Ramon da Silva Souza, Rhabersh Sales Rodrigues Pascoal, Gabriel Santos da Silva, Lucas Felix Cabral da Silva', 'Ciências Biológicas', false, 2),
        (78, 'ANÁLISE COMPORTAMENTAL DE GUAXINIM MÃO-PELADA (PROCYON CANCRIVORUS) ATRAVÉS DA TÉCNICA DE ENRIQUECIMENTO AMBIENTAL SENSORIAL', 'Maysa Emanuela da Silva Rocha Holanda Carvalho, Luiza Panini, Débora Karine Souza Lopes', 'Ciências Agrárias', false, 2),
        (79, 'A INFLUÊNCIA DA TECNOLOGIA NA EDUCAÇÃO MODERNA', 'Ana Clara Silva, Beatriz Costa', 'Educação', false, 2),
        (80, 'ANÁLISE DO IMPACTO AMBIENTAL DE RESÍDUOS ELETRÔNICOS', 'Carlos Eduardo, Fabiana Alves', 'Meio Ambiente', false, 2),
        (81, 'O USO DE DRONES NA AGRICULTURA', 'Débora Santos, Eduardo Lima', 'Tecnologia Agrícola', false, 2),
        (82, 'INTELIGÊNCIA ARTIFICIAL EM DIAGNÓSTICOS MÉDICOS', 'Fernanda Costa, Gabriel Silva', 'Ciências da Saúde', false, 2),
        (83, 'BLOCKCHAIN: UMA REVOLUÇÃO NO MERCADO FINANCEIRO', 'Helena Souza, Igor Almeida', 'Tecnologia Financeira', false, 2),
        (84, 'A INFLUÊNCIA DA MÚSICA NO DESENVOLVIMENTO INFANTIL', 'Juliana Carvalho, Marcos Vinícius', 'Psicologia', false, 2),
        (85, 'USO DE ENERGIA SOLAR EM EDIFICAÇÕES RESIDENCIAIS', 'Laura Menezes, Rafael Andrade', 'Sustentabilidade', false, 2),
        (86, 'BIG DATA: ANALISANDO GRANDES VOLUMES DE DADOS', 'Mariana Silva, Pedro Oliveira', 'Tecnologia da Informação', false, 2),
        (87, 'A EVOLUÇÃO DO E-COMMERCE NOS ÚLTIMOS ANOS', 'Nathalia Souza, Otávio Lima', 'Economia', false, 2),
        (88, 'O IMPACTO DAS MUDANÇAS CLIMÁTICAS NA BIODIVERSIDADE', 'Paula Fernandes, Ricardo Alves', 'Meio Ambiente', false, 2),
        (89, 'DESAFIOS DA SEGURANÇA CIBERNÉTICA NA ERA DIGITAL', 'Sara Moreira, Thiago Santos', 'Tecnologia da Informação', false, 2),
        (90, 'AVANÇOS NA TECNOLOGIA DE IMPRESSÃO 3D', 'Tatiana Lopes, Vinícius Costa', 'Engenharia', false, 2),
        (91, 'INOVAÇÕES NO DESENVOLVIMENTO DE VACINAS', 'Yasmin Gomes, Yuri Almeida', 'Ciências da Saúde', false, 2),
        (92, 'A IMPORTÂNCIA DA LEITURA NA PRIMEIRA INFÂNCIA', 'Zélia Costa, Arthur Souza', 'Educação', false, 2),
        (93, 'TECNOLOGIAS EMERGENTES NA INDÚSTRIA 4.0', 'Bianca Lima, Caio Oliveira', 'Engenharia', false, 2),
        (94, 'A PSICOLOGIA DAS CORES NO MARKETING', 'Daniela Souza, Eduardo Andrade', 'Marketing', false, 2);           
        """
    )
    op.execute(
        """
        SELECT setval('papers_id_seq', 94, false);
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
